version: '3.4'

services:
  blendify:
    image: blendify
    build:
      context: .
      dockerfile: ./Dockerfile
      target: main
    ports:
      - 5000:5000
      - 5678:5678
    env_file:
      - .env
    volumes:
      - ./src:/app/src
  frontend:
    image: blendify-fe
    build:
      context: .
      dockerfile: ./Dockerfile.fe
    ports:
      - 5001:5001
    volumes:
      - ./src/frontend:/app/src/frontend
  cache:
    image: redis:latest
    ports:
      - 6379:6379
