version: '3.4'

services:
  blendify:
    container_name: blendify
    image: blendify
    build:
      context: .
      dockerfile: ./build/server/Dockerfile
      target: main # debugpy
    ports:
      - 5000:5000
      - 5678:5678
    env_file:
      - .env
    volumes:
      - ./src:/app/src
  frontend:
    container_name: blendify-fe
    image: blendify-fe
    build:
      context: .
      dockerfile: ./build/frontend/Dockerfile
    ports:
      - 5001:5001
    volumes:
      - ./src/frontend:/app/src/frontend
  blendify-cache:
    container_name: blendify-cache
    image: blendify-cache
    build: 
      context: .
      dockerfile: ./build/redis/Dockerfile
    ports:
      - 6379:6379
