version: '3.4'

services:
  blendify:
    container_name: blendify
    image: blendify
    build:
      context: .
      dockerfile: ./build/dev/server/Dockerfile
      target: main # debugpy
    ports:
      - 5000:5000
      - 5678:5678
    environment:
      - SPOTIFY_CLIENT_SECRET=update_me
      - SPOTIFY_CLIENT_ID=update_me
      - CACHE_HOST=blendify-cache
      - CACHE_PORT=6379
      - CACHE_USER=user
      - CACHE_PASS=pass
      - APP_HOST=127.0.0.1
      - FLASK_SECRET_KEY=50ca850dc563343d820186c26a220a48dd8cc0dc252f8cec7e60057f496c7e72
      - FLASK_SERVER_NAME=127.0.0.1:5000
      - FLASK_FRONTEND_SERVER_NAME=127.0.0.1:5001
      - FLASK_ENV=development
    volumes:
      - ./src:/app/src
  frontend:
    container_name: blendify-fe
    image: blendify-fe
    build:
      context: .
      dockerfile: ./build/dev/frontend/Dockerfile
    ports:
      - 5001:5001
    volumes:
      - ./src/frontend:/app/src/frontend
  blendify-cache:
    container_name: blendify-cache
    image: blendify-cache
    build: 
      context: .
      dockerfile: ./build/dev/redis/Dockerfile
    ports:
      - 6379:6379
